/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MRouteImport } from './routes/m'
import { Route as DesktopRouteImport } from './routes/_desktop'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as DesktopIndexRouteImport } from './routes/_desktop.index'
import { Route as MShopRouteImport } from './routes/m.shop'
import { Route as MContactRouteImport } from './routes/m.contact'
import { Route as DesktopQuoteRouteImport } from './routes/_desktop.quote'
import { Route as DesktopProductsRouteImport } from './routes/_desktop.products'
import { Route as DesktopDeliveryRouteImport } from './routes/_desktop.delivery'
import { Route as DesktopContactRouteImport } from './routes/_desktop.contact'
import { Route as DesktopAboutRouteImport } from './routes/_desktop.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopRoute = DesktopRouteImport.update({
  id: '/_desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const DesktopIndexRoute = DesktopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesktopRoute,
} as any)
const MShopRoute = MShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => MRoute,
} as any)
const MContactRoute = MContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MRoute,
} as any)
const DesktopQuoteRoute = DesktopQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopProductsRoute = DesktopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopDeliveryRoute = DesktopDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopContactRoute = DesktopContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DesktopRoute,
} as any)
const DesktopAboutRoute = DesktopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DesktopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DesktopIndexRoute
  '/m': typeof MRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof DesktopAboutRoute
  '/contact': typeof DesktopContactRoute
  '/delivery': typeof DesktopDeliveryRoute
  '/products': typeof DesktopProductsRoute
  '/quote': typeof DesktopQuoteRoute
  '/m/contact': typeof MContactRoute
  '/m/shop': typeof MShopRoute
  '/m/': typeof MIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof DesktopAboutRoute
  '/contact': typeof DesktopContactRoute
  '/delivery': typeof DesktopDeliveryRoute
  '/products': typeof DesktopProductsRoute
  '/quote': typeof DesktopQuoteRoute
  '/m/contact': typeof MContactRoute
  '/m/shop': typeof MShopRoute
  '/': typeof DesktopIndexRoute
  '/m': typeof MIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desktop': typeof DesktopRouteWithChildren
  '/m': typeof MRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_desktop/about': typeof DesktopAboutRoute
  '/_desktop/contact': typeof DesktopContactRoute
  '/_desktop/delivery': typeof DesktopDeliveryRoute
  '/_desktop/products': typeof DesktopProductsRoute
  '/_desktop/quote': typeof DesktopQuoteRoute
  '/m/contact': typeof MContactRoute
  '/m/shop': typeof MShopRoute
  '/_desktop/': typeof DesktopIndexRoute
  '/m/': typeof MIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/products'
    | '/quote'
    | '/m/contact'
    | '/m/shop'
    | '/m/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/delivery'
    | '/products'
    | '/quote'
    | '/m/contact'
    | '/m/shop'
    | '/'
    | '/m'
  id:
    | '__root__'
    | '/_desktop'
    | '/m'
    | '/sitemap.xml'
    | '/_desktop/about'
    | '/_desktop/contact'
    | '/_desktop/delivery'
    | '/_desktop/products'
    | '/_desktop/quote'
    | '/m/contact'
    | '/m/shop'
    | '/_desktop/'
    | '/m/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DesktopRoute: typeof DesktopRouteWithChildren
  MRoute: typeof MRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desktop': {
      id: '/_desktop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/_desktop/': {
      id: '/_desktop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DesktopIndexRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/m/shop': {
      id: '/m/shop'
      path: '/shop'
      fullPath: '/m/shop'
      preLoaderRoute: typeof MShopRouteImport
      parentRoute: typeof MRoute
    }
    '/m/contact': {
      id: '/m/contact'
      path: '/contact'
      fullPath: '/m/contact'
      preLoaderRoute: typeof MContactRouteImport
      parentRoute: typeof MRoute
    }
    '/_desktop/quote': {
      id: '/_desktop/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof DesktopQuoteRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/_desktop/products': {
      id: '/_desktop/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof DesktopProductsRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/_desktop/delivery': {
      id: '/_desktop/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DesktopDeliveryRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/_desktop/contact': {
      id: '/_desktop/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof DesktopContactRouteImport
      parentRoute: typeof DesktopRoute
    }
    '/_desktop/about': {
      id: '/_desktop/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DesktopAboutRouteImport
      parentRoute: typeof DesktopRoute
    }
  }
}

interface DesktopRouteChildren {
  DesktopAboutRoute: typeof DesktopAboutRoute
  DesktopContactRoute: typeof DesktopContactRoute
  DesktopDeliveryRoute: typeof DesktopDeliveryRoute
  DesktopProductsRoute: typeof DesktopProductsRoute
  DesktopQuoteRoute: typeof DesktopQuoteRoute
  DesktopIndexRoute: typeof DesktopIndexRoute
}

const DesktopRouteChildren: DesktopRouteChildren = {
  DesktopAboutRoute: DesktopAboutRoute,
  DesktopContactRoute: DesktopContactRoute,
  DesktopDeliveryRoute: DesktopDeliveryRoute,
  DesktopProductsRoute: DesktopProductsRoute,
  DesktopQuoteRoute: DesktopQuoteRoute,
  DesktopIndexRoute: DesktopIndexRoute,
}

const DesktopRouteWithChildren =
  DesktopRoute._addFileChildren(DesktopRouteChildren)

interface MRouteChildren {
  MContactRoute: typeof MContactRoute
  MShopRoute: typeof MShopRoute
  MIndexRoute: typeof MIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MContactRoute: MContactRoute,
  MShopRoute: MShopRoute,
  MIndexRoute: MIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DesktopRoute: DesktopRouteWithChildren,
  MRoute: MRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
