/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WbeRouteImport } from './routes/wbe'
import { Route as StoneRouteImport } from './routes/stone'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MulchRouteImport } from './routes/mulch'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdditionalRouteImport } from './routes/additional'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WbeRoute = WbeRouteImport.update({
  id: '/wbe',
  path: '/wbe',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneRoute = StoneRouteImport.update({
  id: '/stone',
  path: '/stone',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MulchRoute = MulchRouteImport.update({
  id: '/mulch',
  path: '/mulch',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditionalRoute = AdditionalRouteImport.update({
  id: '/additional',
  path: '/additional',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/additional': typeof AdditionalRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/mulch': typeof MulchRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone': typeof StoneRoute
  '/wbe': typeof WbeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/additional': typeof AdditionalRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/mulch': typeof MulchRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone': typeof StoneRoute
  '/wbe': typeof WbeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/additional': typeof AdditionalRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/mulch': typeof MulchRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stone': typeof StoneRoute
  '/wbe': typeof WbeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/additional'
    | '/contact'
    | '/delivery'
    | '/mulch'
    | '/privacy'
    | '/quote'
    | '/service-area'
    | '/sitemap.xml'
    | '/stone'
    | '/wbe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/additional'
    | '/contact'
    | '/delivery'
    | '/mulch'
    | '/privacy'
    | '/quote'
    | '/service-area'
    | '/sitemap.xml'
    | '/stone'
    | '/wbe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/additional'
    | '/contact'
    | '/delivery'
    | '/mulch'
    | '/privacy'
    | '/quote'
    | '/service-area'
    | '/sitemap.xml'
    | '/stone'
    | '/wbe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdditionalRoute: typeof AdditionalRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  MulchRoute: typeof MulchRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoneRoute: typeof StoneRoute
  WbeRoute: typeof WbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wbe': {
      id: '/wbe'
      path: '/wbe'
      fullPath: '/wbe'
      preLoaderRoute: typeof WbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone': {
      id: '/stone'
      path: '/stone'
      fullPath: '/stone'
      preLoaderRoute: typeof StoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulch': {
      id: '/mulch'
      path: '/mulch'
      fullPath: '/mulch'
      preLoaderRoute: typeof MulchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additional': {
      id: '/additional'
      path: '/additional'
      fullPath: '/additional'
      preLoaderRoute: typeof AdditionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdditionalRoute: AdditionalRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  MulchRoute: MulchRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoneRoute: StoneRoute,
  WbeRoute: WbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
